// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum OuterEnum: String, CaseIterable, Codable {
	case placed
	case approved
	case delivered
}
