// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum EnumClass: String, Codable, Hashable, Sendable {
    case abc = "_abc"
    case minusefg = "-efg"
    case xyz = "(xyz)"
}
