// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A classification of the file. For example to identify it as generated.
public enum CodeScanningAlertClassification: String, CaseIterable, Codable {
    case source
    case generated
    case test
    case library
}
