// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

enum EnumClass: String, CaseIterable, Codable {
    case abc = "_abc"
    case minusefg = "-efg"
    case xyz = "(xyz)"
}
