// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct EnumArrays: Codable {
    public var justSymbol: JustSymbol?
    public var arrayEnum: [ArrayEnumItem]?

    public enum JustSymbol: String, CaseIterable, Codable {
        case greaterThanOrEqualTo = ">="
        case dollar = "$"
    }

    public enum ArrayEnumItem: String, CaseIterable, Codable {
        case fish
        case crab
    }

    public init(justSymbol: JustSymbol? = nil, arrayEnum: [ArrayEnumItem]? = nil) {
        self.justSymbol = justSymbol
        self.arrayEnum = arrayEnum
    }

    private enum CodingKeys: String, CodingKey {
        case justSymbol = "just_symbol"
        case arrayEnum = "array_enum"
    }
}
